channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - pyg
  - aihabitat
dependencies:
  - gcc=11.2.0
  - gxx=11.2.0
  - sysroot_linux-64==2.17
  - binutils>=2.36
  - cudatoolkit-dev=11.7
  - python=3.9
  - cmake
  - pybind11
  - setuptools
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch3d
  - torchvision
  - torchaudio
  - mkl=2024.0
  - pyg
  - pip
  - habitat-sim=0.2.5
  - pip: 
    - setuptools <70