name: objectnav-zoo
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - pyg
  - aihabitat
dependencies:
  - python==3.9.*
  - cmake>=3.5
  - pybind11
  - gcc=10.4.0
  - gxx=10.4.0
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - withbullet
  - habitat-sim==0.2.5
  - pytorch3d
  - torchvision
  - torchaudio
  - mkl=2024.0
  - pyg
  - pytorch-cluster
  - pytorch-scatter
  - exa # optional: nice ls
  - fzf # optional: fancy ctrl + R
  - pip
  - pip:
    - gym>=0.22.0,<0.23.1
    - yacs>=0.1.8
    - attrs>=19.1.0
    - numpy <1.24 # certain deprecated operations were used in other deps
    - numba <0.60
    - scipy
    - pybullet
    - trimesh<4
    - pytest
    - scikit-image
    - scikit-fmm
    - scikit-learn
    - numpy-quaternion
    - natsort
    - frozendict
    # Robots
    - opencv-python
    - pin>=2.6.17
    # Neural networks
    - openai-clip
    - timm
    - pandas>=2
    - mss
    # visualizations and debugging
    - matplotlib>=3
    # Command line tools
    - click
    # data tools
    - pillow<10.0.0
    - atomicwrites
    - loguru
    - yacs
    - h5py>=3.9
    - imageio
    - pygifsicle
    - pynput
      # - git+https://github.com/openai/CLIP.git
    - open3d>=0.17
    - imutils
    - natsort
    - scikit-fmm
    - scikit-learn
    - scikit-image
    - trimesh

